project                 = "edblack"
region                  = "us-central1"
zone                    = "us-central1-a"
phone_number_enabled    = "true"
# test_phone_numbers      = "+11231231234 = 000000"
allow_duplicate_emails  = "true"
email_enabled           = "true"
email_password_required = "false"
